name: Build Windows Installer

on:
  release:
    types: [published]  

jobs:
  build:
    runs-on: windows-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4


      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install PyInstaller
        run: pip install pyinstaller


      - name: Generate PyInstaller Spec
        run: |
          echo '
          block_cipher = None
          a = Analysis(
              ["main.py"],
              pathex=[],
              binaries=[],
              datas=[("assets/*", "assets")],
              hiddenimports=[],
              hookspath=[],
              hooksconfig={},
              runtime_hooks=[],
              excludes=[],
              win_no_prefer_redirects=False,
              win_private_assemblies=False,
              cipher=block_cipher,
              noarchive=False,
          )
          pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)
          exe = EXE(
              pyz,
              a.scripts,
              name="MyApp",
              debug=False,
              bootloader_ignore_signals=False,
              strip=False,
              upx=True,
              console=False,
              icon="app.ico"
          )
          ' > build.spec


      - name: Build EXE
        run: pyinstaller build.spec

      - name: Install Inno Setup
        run: choco install innosetup -y --no-progress

      - name: Generate Inno Setup Script
        run: |
          echo '
          [Setup]
          AppName=MyApp
          AppVersion=${{ github.ref_name }}
          AppPublisher=YourName
          DefaultDirName={autopf}\MyApp
          DefaultGroupName=MyApp
          OutputBaseFilename=Software-Setup-win64-${{ github.ref_name }}
          Compression=lzma2
          SolidCompression=yes
          OutputDir=release

          [Files]
          Source: "dist\MyApp.exe"; DestDir: "{app}"; Flags: ignoreversion
          Source: "assets\*"; DestDir: "{app}\assets"; Flags: recursesubdirs

          [Icons]
          Name: "{group}\MyApp"; Filename: "{app}\MyApp.exe"
          Name: "{commondesktop}\MyApp"; Filename: "{app}\MyApp.exe"
          ' > setup.iss

      - name: Compile Installer
        run: ISCC.exe setup.iss

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: release/Software-Setup-win64-${{ github.ref_name }}.exe
